entryPoints:
  web:
    address: ":8000"
    http:
      redirections:
        entryPoint:
          to: websecure
    asDefault: true
  websecure:
    address: ":8443"
    http:
      tls:
        certResolver: dnsresolver
    asDefault: true
  websecure-external:
    address: ":8886"
    http:
      tls:
        certResolver: dnsresolver
  # metrics:
  #     address: ":8082"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/file
    watch: true

certificatesResolvers:
  dnsresolver:
    acme:
      email: yusefkarim@riseup.net
      storage: /etc/traefik/acme/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnschallenge:
        provider: porkbun
        # Need to use external resolver due to internal DNS server zone entry (multiple SOA problem)
        resolvers: ["9.9.9.9"]
      keyType: EC256

api:
  dashboard: true

# metrics:
#     prometheus:
#         entryPoint: metrics

log:
  format: json

accessLog:
  format: json
