http:
    middlewares:
        oauth2-proxy:
            forwardAuth:
                address: http://oauth2-proxy:4180/
                trustForwardHeader: true
                authResponseHeaders:
                    - X-Auth-Request-Access-Token
                    - Authorization
